### ISSUE TITLE
Off() method not exposed in HubConnection

### ISSUE THREAD

**Issue by rpedretti** [BlazorExtensions/SignalR#10]
The `Off()` method is implemented in the `HubConnectionManager` but not exposed trough `HubConnection` like the `On<T>()` Method

How do I unregister a function then?

Thanks!

**Comment by galvesribeiro** [comment]
You should not call directly the Off, hence why it wasn't exposed. When you call `On<T>()`, it will return a `IDisposable`.

All you have todo is call `Dispose()` on it as in the regular SignalR C# library.

Look at the samples here https://github.com/BlazorExtensions/SignalR/blob/master/test/Blazor.Extensions.SignalR.Test.Client/Pages/ChatComponent.cs#L66

Let me know if you have any problems with it.

**Comment by galvesribeiro** [comment]
I'm closing it but let me know if you wasn't able to use the method explained. Thanks!
