### ISSUE TITLE
Update JavaScript interop to new spec

### ISSUE THREAD

**Issue by danielmeza** [BlazorExtensions/SignalR#11]
Hi @galvesribeiro  this is for track the update to new interop spec

**Comment by galvesribeiro** [comment]
Thanks! 

I'm working on it.

Will let you know here soon.

**Comment by danielmeza** [comment]
Great! do you acept more forkers?

**Comment by danielmeza** [comment]
@galvesribeiro  I made a PR https://github.com/BlazorExtensions/SignalR/pull/12

**Comment by galvesribeiro** [comment]
Thanks for the PR! I'll review it when I get to the SignalR component. Working on the others now. 

Thanks!

**Comment by galvesribeiro** [comment]
Hello @danielmeza! As I mentioned on the [PR here](https://github.com/BlazorExtensions/SignalR/pull/12#issuecomment-408579638), I decided to use the new non-static interop mode and that goes totally different from the way the code was and your PR as well so I close it.

Again, thank you very much for the PR, I really appreciate that, and looking forward for other contributions!

Thanks!
