### ISSUE TITLE
Casting JSRuntime.Current to IJSInProcessRuntime

### ISSUE THREAD

**Issue by AndreasTruetschel** [BlazorExtensions/SignalR#16]
At several places, the current js-runtime is cast to IJSInProcessRuntime. This seems to be ok for the default case, but is this really safe to do with future cases in mind?  

My proposal is to add a helper (extension method) that performs this cast, with a workaround, for the case, that the js-runtime is not an in-processes runtime and substitute all occurances of the cast.
This could look like this:
```
internal static class JSRuntimeExtensions
{
    public static T InvokeSync<T>(
        this IJSRuntime jsRuntime, 
        string identifier, 
        params object[] args)
    {
        if (jsRuntime == null)
            throw new ArgumentNullException(nameof(jsRuntime));

        if(jsRuntime is IJSInProcessRuntime inProcessJsRuntime)
        {
           return inProcessJsRuntime.Invoke<T>(identifier, args);
        }

        return jsRuntime.InvokeAsync<T>(identifier, args)
                                  .ConfigureAwait(false)
                                  .GetAwaiter()
                                  .GetResult();
    }
}
```

This solution is not ideal either and should be handled with care.

**Comment by galvesribeiro** [comment]
@AndreasTruetschel thanks! Merged.
