### ISSUE TITLE
Add Streaming APIs support

### ISSUE THREAD

**Issue by galvesribeiro** [BlazorExtensions/SignalR#2]
Implement SignalR streaming APIs as per https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-2.1

**Comment by michaelp** [comment]
@galvesribeiro - any updates on the progress with this story?

**Comment by vavjeeva** [comment]
@galvesribeiro i am also looking for streaming support.

**Comment by acrigney** [comment]
Any updates on this guys?

**Comment by galvesribeiro** [comment]
Hello folks! Not yet, I'm looking to implement in the next couple of months as I'll need it for a project.

If someone has a more urgent need, please let me know and I'll see what I can do.

Thanks!

**Comment by seriouz** [comment]
How do you translate the c# streams to JavaScript? Are there streams in JS, too?

**Comment by galvesribeiro** [comment]
Yeah, JS has it: https://docs.microsoft.com/en-us/aspnet/core/signalr/streaming?view=aspnetcore-2.2#javascript-client

I need to make a mapper between both sides and probably use something like `IObservable<T>` on .Net side... Need to invest a bit of time on it.

**Comment by galvesribeiro** [comment]
*DEPRECATION NOTE*: This package is no longer required since [Blazor WebAssembly now supports SignalR Client](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/). Users of this package should stop using it and use the official client instead.
