### ISSUE TITLE
Object of type 'System.Int64' cannot be converted to type 'System.UInt32'

### ISSUE THREAD

**Issue by Apollo3zehn** [BlazorExtensions/SignalR#21]
I am using an ASP.NET Server hosting a Blazor application + SignalR server. My browser app communicates to that server via BlazorExtensions/SignalR using MessagePack (but same problem with JSON). When I try to serialize a simple class consisting of an enum and an uint32 field, I get the following errors:

**enum:** Input string was not in a correct format.
**uint32:** Object of type 'System.Int64' cannot be converted to type 'System.UInt32'

I am not sure what exactly causes the issues but I think that it can be easily reproduced (or not) if you extend your tests with enum and uint32 fields.

Thank you

**Comment by galvesribeiro** [comment]
can you check if that still happen on the latest package?

**Comment by Apollo3zehn** [comment]
It does not happen anymore for Enums (good thing!), but still for unsigned numbers. I think I found the reason, see here: https://github.com/aspnet/Extensions/issues/1701

I`ll close this issue, since it is out of the scope of this repository. Hopefully it will be fixed in the next preview :)

**Comment by Apollo3zehn** [comment]
Ok I got a littble bit confused with MessagePack and JSON because I tried both. 

For MessagePack, both, ```enum``` and ```uint```, do not work. I guess it is because MessagePack serializes the enum in an unexpected way. The JSON string passed to the ```On<T1, T2, ...>()``` method in the ```HubConnection``` class looks like the following (content of variable ```payloads[0]```):

**MessagePack:** 
```{"Id":1,"StringData":"Demo Data","UIntData":1,"EnumData":"Mode1"}```: 

**vs.**

**JSON:** 
```{"Id":1,"StringData":"Demo Data","UIntData":1,"EnumData":"1"}```

So, with MessagePack, the EnumData property is a string instead of a number.

With JSON-only transport, enum is working but ```uint``` not. The reason seems to be in the SimpleJson serializer as written above.

I also tried with the brand new JsonSerializer in System.Text.Json.Serialization (```JsonSerializer.Parse<DemoData>(jsonString);```. This serialize is able to handle ```uint``` correctly, but I think it is only available in netcore3.0 apps.

**Comment by galvesribeiro** [comment]
Please check the test project now. I've added a sample of an `enum : uint` that enumerate your case so it must work for you. No changes were made to the packages. Only the sample.

I'm closing the issue but feel free to ping back in case you fall in troubles.

Thanks!
