### ISSUE TITLE
Build() just.. hangs.

### ISSUE THREAD

**Issue by Kiiyya** [BlazorExtensions/SignalR#22]
I'm trying to recreate https://youtu.be/Yb-N0TmEq_Y?t=2275 and I have no clue why, but it just hangs exactly [here](https://kiiyya.visualstudio.com/_git/RazorCompionents%20Mess?path=%2FRazorCompionietns%2FRazorCompionietns.App%2FPages%2FChat.cshtml&version=GCa97d77ef3a00d403347ceeba3f2e1713c61732d0&line=31&lineStyle=plain&lineEnd=31&lineStartColumn=26&lineEndColumn=35). I set a breakpoint on that line and on line 32, hit continue, and nothing happens, no console output in the browser, and the nav menu (when I want to go to Counter or others) are not responsive.

Debugger stepping into doesn't work, and I'm not a blazor pro and not a web dev pro, so I'm kinda stuck. I'm using VS2019 preview with asp.net 3 and RazorComponents. All of that is preview heh.

**Comment by EricPalmer22** [comment]
I have this same issue as well in a .NET 3.0 preview Razor Components project

**Comment by EricPalmer22** [comment]
I was actually able to get SignalR working in my Razor Components project without any additional blazor extensions. I can try to help you Kiiyya with it later today when I am home from work

**Comment by pbeaty** [comment]
How?

**Comment by galvesribeiro** [comment]
We've updated to preview4, check the new nuget package.
