### ISSUE TITLE
Update to Blazor 0.9.0

### ISSUE THREAD

**Issue by moonreign** [BlazorExtensions/SignalR#25]
Blazor reached version 0.9.0, SignalR should upgrade too.
Potentially some dependencies like Blazor.Extensions.Logging will need to be upgraded to 0.9.0 first.

**Comment by Richard809** [comment]
I think that will fix this **issue**:

The type 'IWebAssemblyHostBuilder' exists in both 'Microsoft.AspNetCore.Blazor.Browser, Version=0.7.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' and 'Microsoft.AspNetCore.Blazor, Version=0.9.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'

**Comment by galvesribeiro** [comment]
We've updated to preview4, check the new nuget package.

**Comment by nvmkpk** [comment]
I needed this for blazor version 0.9.0. I am using asp.net core 3.0 preview 3. At this time I cannot update to preview 4.
