### ISSUE TITLE
Option to unsubscribe from the hub

### ISSUE THREAD

**Issue by basbakkernipo** [BlazorExtensions/SignalR#34]
I would like the option to unsubscribe a handle from the hub, is that possible?

**Comment by darkpq** [comment]
The thing that took me along time to realize is that when you call 
`connection.On(methodName, handler)`
 it returns an "IDisposable" object which references the hubCallbackMethod internally.

All you need to do is track which methods you register and dispose of them appropriately.

```
// in your hubconnection class or provider

private static IDictionary<string, IDisposable> _registeredMethods;

public HubConnection Connection { get; set; };

// Connection builder
public async Task ConnectToServer();
{
    // your endpoint and Connection.StartAsync() method
}

public void RegisterMethod(string methodName, Func<yourReturnType, yourParameters> handler)
{
    // null checks, other code etc

    var methodDisposer = Connection.On(methodName, handler);

    _registeredMethods.Add(methodName, methodDisposer)'
}

public void UnRegisterMethod(string methodName);
{
    // check if key exists etc.

    _registeredMethods[methodName].Dispose();
    _registeredMethods.Remove(methodName);
}
```

**Comment by galvesribeiro** [comment]
Yes. That is expected behaviour as in the official .Net client. 

I'm closing the issue as we don't have any actions to move forward. Please let me know if you still have any issues with the `IDisposable.Dispose()`.
