### ISSUE TITLE
[Question] - Reason for this library?

### ISSUE THREAD

**Issue by dazinator** [BlazorExtensions/SignalR#37]
I am looking to use signalr client in my blazor (client side) app.
My first thought was to add the official signalr.client nuget package:

```
<PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="3.0.0-preview6.19307.2" />
```

Then I stumbled accross this project which wraps the typescript version - i'm assuming there must be a reason why the `Microsoft.AspNetCore.SignalR.Client` package I have referenced above won't work in blazor client applications and why this project exists? Are you able to clarify what the reason is as that will help me decide what to do!

Cheers

**Comment by galvesribeiro** [comment]
@dazinator the reason for that is that neither `HttpClient` nor `WebSockets` are supported at the client side.

You can use that package on Blazor running in server-side mode.

If you want to run on client-side/WASM mode, you will need the JavaScript client.

This package wraps the JS client and mimics the full server-side client API as much as possible so the change should be as smooth as possible.

Please let me know if that answer you question properly. For now I'm closing the issue.

Thanks!

**Comment by dazinator** [comment]
Thanks for the explanation. 

I'm a little confused about one part of this statement:
> neither HttpClient nor WebSockets are supported at the client side.

I'm using `HttpClient` fine from a client side blazor app - it's constructed using the web assembly http handler which marshalls requests through javascript fetch api.  So if HttpClient works in Blazor I'm assuming the problem must be that signalr client doesnt allow you to pass your own http client or something?

**Comment by dazinator** [comment]
By the way thanks for thi als library it is working well in my application (preview 6)

**Comment by galvesribeiro** [comment]
> By the way thanks for this library it is working well in my application (preview 6)

No problem.

> I'm using HttpClient fine from a client side blazor app - it's constructed using the web assembly http handler which marshalls requests through javascript fetch api

Yeah I think my answer was not _that_ accurate... SignalR client is based on the new transport abstractions just like the server. One can theoretically implement it by wrapping the correct APIs on JS/WASM. The current implementation don't work now.

This package was also created before that abstrations were in place. So if you find the correct way to implement it, please suggest it in an issue and perhaps if you feel in the mood, feel free to make a PR. 

I always love to get rid of JS 😄 

Thanks!

**Comment by vavjeeva** [comment]
> I'm using `HttpClient` fine from a client side blazor app - it's constructed using the web assembly http handler which marshalls requests through javascript fetch api. So if HttpClient works in Blazor I'm assuming the problem must be that signalr client doesnt allow you to pass your own http client or something?

signalR client on client side blazor is not supported yet due to websocket support in runtime which is not enabled yet. You can see the response from dan in the below link.

https://github.com/aspnet/AspNetCore/issues/9825#issuecomment-488028164
