### ISSUE TITLE
Serverside example

### ISSUE THREAD

**Issue by cwschroeder** [BlazorExtensions/SignalR#45]
Nice work! But is there a way to use this extension with serverside blazor?
I tried to follow this guide [https://github.com/Suchiman/BlazorDualMode](BlazorDualMode) to switch between clientside and serverside however when I try serverside, the page hangs during load without a good error message.

**Comment by galvesribeiro** [comment]
Hello @cwschroeder 

The server-side mode doesn't require this package.

I recommend you to have an abstraction and/or factory that dan return to you based on the environment from the DualMode example, the correct implementation.

The server-side mode uses the official SignalR client for .Net.

**Comment by cwschroeder** [comment]
Thanks for clarifying. I will try to use a factory as you suggested.

**Comment by galvesribeiro** [comment]
Sure, I'm closing the issue but feel free to ping if you have any problems.
