### ISSUE TITLE
JsRuntime on Server side

### ISSUE THREAD

**Issue by tjmcnaboe** [BlazorExtensions/SignalR#46]
I get this error using server side:  InvalidOperationException: JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.  I can't seem to figure out how to get around it,

Perhaps related to this?
https://github.com/aspnet/AspNetCore/issues/11159

**Comment by galvesribeiro** [comment]
Hello!

Please check the README.md. It states that this component is for client-side blazor. Server Side Blazor don't need it and can use the official signalR client.
