### ISSUE TITLE
InvalidOperationException: JSRuntime must be set up correctly and must be an instance of JSRuntimeBase to use DotNetObjectRef.

### ISSUE THREAD

**Issue by soundariyaa** [BlazorExtensions/SignalR#47]
I have created a blazor server app in Visual studio preview 2019 and Blazor.Extensions.SignalR (0.2.0). Getting an error when I am trying to listen the signalR message and reloading the table.Do I missed any namespace or something else? 

Here my code is,
ViewLog.razor file 
@page "/ViewLog"
@using Telerik.Blazor;
@using Telerik.Blazor.Components.Grid;
@using Microsoft.WindowsAzure.Storage;
@using Microsoft.WindowsAzure.Storage.Table;
@using System.Threading.Tasks;
@using WcomLogViewerBlazor.Models;
@using Microsoft.Azure.Documents;
@using Blazor.Extensions;
@using Microsoft.AspNetCore.SignalR;
@using Microsoft.Extensions.DependencyInjection;
@using System.Net.Http;
@using Microsoft.JSInterop;
@using Newtonsoft.Json;

    [Inject] private HubConnectionBuilder _hubConnectionBuilder { get; set; }
    private HubConnection connection;
    private IJSRuntime _runtime;
    // Listen SignalR messages and update table
    protected override async Task OnInitAsync()
    {
        var BaseUrl = "http://localhost:7071/api/SignalRInfo";
        var resonse = await client.GetStringAsync(BaseUrl);
        var responseInfo = JsonConvert.DeserializeObject<Models.ConnectionInfo>(resonse as string);
        var URL = responseInfo.URL;
        var token = responseInfo.AccessToken;
        this.connection = this._hubConnectionBuilder
            .WithUrl(URL,
            opt =>
        {
            opt.LogLevel = SignalRLogLevel.Trace; // Client log level
        opt.Transport = HttpTransportType.WebSockets; // Which transport you want to use for this connection
    }) .Build();
        connection.On<string>("TableUpdated", this.OnBroadcastMessage);
           await this.connection.StartAsync();
    }

startup.cs
  
            services.AddTelerikBlazor();
            services.AddTransient<HubConnectionBuilder>();
            services.AddSignalR();
            

Project.csproj file
  <ItemGroup>
    <PackageReference Include="Blazor.Extensions.SignalR" Version="0.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.Cosmos.Table" Version="1.0.1" />
    <PackageReference Include="Microsoft.Azure.SignalR" Version="1.1.0-preview1-10442" />
    <PackageReference Include="Telerik.DataSource" Version="1.0.0" />
    <PackageReference Include="Telerik.UI.for.Blazor" Version="1.4.1" />
    <PackageReference Include="WindowsAzure.Storage" Version="9.3.3" />
  </ItemGroup>

**Comment by galvesribeiro** [comment]
Hello, thanks for the info.

However, I think you are on the wrong place here. You are using the official Microsoft Client for SignalR. That is only available on Blazor Server Side.

This repo here however, only focus on the client side.

Thank you! I'm closing the issue.

**Comment by soundariyaa** [comment]
Thanks for your replay .I have just installed "SignalR.Client" namespace but I never used that namespace anywhere in my project.I suppose to uninstall it. Actually I have created Hub in Azure function serverless application.Here In Blazor application ,sending request to get a connection info from Azure serverless Application and pass the "SignalR Service URL" to establish the conncetion .   


Here is code where I used for Hub creation :

public static class SignalRInfo
    {
        [FunctionName("SignalRInfo")]
        public static IActionResult Run(
          [HttpTrigger(AuthorizationLevel.Anonymous)] HttpRequest req,
          [SignalRConnectionInfo(HubName = "ViewLogger")] SignalRConnectionInfo connectionInfo,
          ILogger log)
        {
            return new OkObjectResult(connectionInfo);
        }
    }

Function for sending Message to SignalR:

 public static void Run([QueueTrigger("logqueue")]string myQueueItem,
                 [Table("LogJournal"), StorageAccount("AzureWebJobsStorage")] ICollector<Models.LogItem> items,
                 [SignalR(HubName = "ViewLogger")] IAsyncCollector<SignalRMessage> signalRMessage, 
                 ILogger log)

This is output for azure serverless Apllication:

Http Functions:

        SignalRInfo:  http://localhost:7071/api/SignalRInfo

        WriteLog: [GET,POST] http://localhost:7071/api/WriteLog

[14/08/2019 14:29:18] Host lock lease acquired by instance ID '0000000000000000000000000A68584A'.
