### ISSUE TITLE
[Request] Add Off functionality to unregister callbacks

### ISSUE THREAD

**Issue by rpedretti** [BlazorExtensions/SignalR#5]
It would be nice to have it in both `Off("name", callback)` and `Off("name")` to unregister all call-backs for `"name"`

**Comment by galvesribeiro** [comment]
Thanks @rpedretti I'll look at it later tonight. Will keep you posted.

**Comment by rpedretti** [comment]
Thanks! Its a great extension to Blazor! Great job!

**Comment by galvesribeiro** [comment]
Added with #7 and will be out on 0.1.3. Thanks for the request!
