### ISSUE TITLE
.net 3 preview 9 build error

### ISSUE THREAD

**Issue by jasjae** [BlazorExtensions/SignalR#52]
Hi, got this error after updating to preview 9:
11>Unhandled Exception: Mono.Linker.MarkException: Error processing method: 'System.Void Blazor.Extensions.HubConnection::.ctor(Microsoft.JSInterop.IJSRuntime,Blazor.Extensions.HttpConnectionOptions)' in assembly: 'Blazor.Extensions.SignalR.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve Microsoft.JSInterop.DotNetObjectRef`1<!!0> Microsoft.JSInterop.DotNetObjectRef::Create(!!0)
11>   at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
11>   at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
11>   at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
11>   at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
11>   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
11>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
11>   --- End of inner exception stack trace ---
11>   at Mono.Linker.Steps.MarkStep.ProcessQueue()
11>   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
11>   at Mono.Linker.Steps.MarkStep.Process()
11>   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
11>   at Mono.Linker.Pipeline.ProcessStep(LinkContext context, IStep step)
11>   at Mono.Linker.Pipeline.Process(LinkContext context)
11>   at Mono.Linker.Driver.Run(ILogger customLogger)
11>   at Mono.Linker.Driver.Execute(String[] args, ILogger customLogger)
11>   at Mono.Linker.Driver.Main(String[] args)

**Comment by AlexanderJohnston** [comment]
I'm seeing something similar right now and trying to diagnose it. I'll check back here if I learn of anything. In the meantime I'm getting a stacktrace like this on the client:


> WASM: ﻿Unhandled exception rendering component: blazor.webassembly.js:1:35128
> 
> WASM: System.TypeLoadException: Could not resolve type with token 0100002b from typeref (expected class 'Microsoft.JSInterop.DotNetObjectRef' in assembly 'Microsoft.JSInterop, Version=3.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') blazor.webassembly.js:1:35128
> 
> WASM:   at Blazor.Extensions.HubConnectionBuilder.Build () <0x2dafe90 + 0x0003c> in <150deb4254614931b9d0e3b9cd8d7a0f>:0 
>

**Comment by AlexanderJohnston** [comment]
To resolve this issue, I installed the package: `System.Threading.Tasks.Extensions`

The `Microsoft.JSInterop.DotNetObjectRef` was embarassingly caused by not updating Blazor.Extensions.SignalR to version 0.4.0

After I updated then I received a warning about missing the ValueTask<T> type. Once I installed `System.Threading.Tasks.Extensions` then SignalR began working as expected.

**Comment by galvesribeiro** [comment]
Please try out latest packages released pacakges.
