### ISSUE TITLE
Serialization Issue / Configuration

### ISSUE THREAD

**Issue by alexfdezsauco** [BlazorExtensions/SignalR#53]
There is a serialization issue. Looks like json serializer configuration. I'm not able to receive deserialized entity as a message. All fields have default values. (case sensitive serialization?) 

Workaround: Serialize as string in server side, send the message as string, and deserialize as entity later.  But I don't want todo this.

Now I'm using Blazor.Extensions.SignalR 0.4.0 but I noticed this behavior since preview 7.

**Comment by alexfdezsauco** [comment]
This work properly https://github.com/csnewman/BlazorSignalR.

**Comment by darkpq** [comment]
I am having the same issue. No build errors, client side code takes the shared C# type as the connection.on<CustomType> ...    type on client side all default values.

**Comment by divinci** [comment]
Yes same issue.

**Comment by divinci** [comment]
I am using aspnet core SignalR on the server side - so to get around this I added

`services.AddSignalR().AddMessagePackProtocol();`

and in Blazor.Extensions.SignalR

`var connection = _hubConnectionBuilder      // the injected one from above.
            .WithUrl("/TradeHub", // The hub URL. If the Hub is hosted on the server where the blazor is hosted, you can just use the relative path.
            opt =>
            {
                opt.EnableMessagePack = true;`

**Comment by divinci** [comment]
I have created a PR #58 that demonstrates the issue.

**Comment by galvesribeiro** [comment]
Please check the new test project. There is no need for new packages. All we need is to use the `JsonPropertyName` attribute which comes with the new serializer from `System.Text.Json`.

**Comment by alexfdezsauco** [comment]
The default serialization configuration is kind of breaking change. But it works with the usage of JsonPropertyName.
