### ISSUE TITLE
HubConnectionBuilder throws NullReferenceException

### ISSUE THREAD

**Issue by jhefreyzz** [BlazorExtensions/SignalR#55]
Hi,

I try incorporating this extension to a blazor app but I encounter an error when establishing a connection.
Here's what I've done which is based on the usage in the README
- [x] Define endpoints for the hub `endpoints.MapHub<TodoHub>("/todoHub")`
- [x] Added `services.AddTransient<HubConnectionBuilder>();` in *Startup.cs*
- [x] Added 
```
[Inject]
 private HubConnectionBuilder _hubConnectionBuilder { get; set; }

protected override async Task OnInitializedAsync()
 {
        HubConnection connection = _hubConnectionBuilder.WithUrl("/todoHub",
            opt =>
            {
               opt.LogLevel = SignalRLogLevel.Trace;
               opt.Transport = HttpTransportType.WebSockets;
           })
        .Build();
        connection.On<string, string>("ReceiveMessage", this.ProcessMessage);
        await connection.StartAsync();
  }
```
With following the steps above what I expect is it will run smoothly but rather it throws NullReferenceException.

The whole stacktrace is [https://gist.github.com/jhefreyzz/eb6194d478e7b43564eabada4e454a07](url)

Uses the latest release from ASP.NET core

**Comment by Daniel-OriginalsUnleashed** [comment]
I am trying to do the same and have followed the same steps. I don't seem to get a thrown error, but the debugger never gets to the next breakpoint below... Looking into it.

**Comment by Daniel-OriginalsUnleashed** [comment]
Sadly no luck with this yet, as I am just learning SignalR with a simple Chat app I used the JS implementation and manipulate the DOM. But this is not good practice in Blazor.

I downloaded the repo and ran it locally, everything worked as expected, so i'm not sure where the issue is. Wasn't able to get debugging working between my project and the package yet.

**Comment by galvesribeiro** [comment]
Not sure were is the problem here.

![image](https://user-images.githubusercontent.com/4714040/67911161-53a2f280-fb64-11e9-9453-0d67d71b7c36.png)

Following the sample it just works...

**Comment by darkpq** [comment]
I have been managing the connection.On(methodName, Method) mapping AFTER a connection is established and it works fine. 

Maybe in your situation try calling your .On() and .OnClose() methods after awaiting the connection?

**Comment by galvesribeiro** [comment]
It shouldn't really matter actually... What cause problems is if you call `.On<>`, don't call `StartAsync()` and then call `Dispose()`...

**Comment by galvesribeiro** [comment]
*DEPRECATION NOTE*: This package is no longer required since [Blazor WebAssembly now supports SignalR Client](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/). Users of this package should stop using it and use the official client instead.
