### ISSUE TITLE
Support automatic reconnects and State on HubConnection 

### ISSUE THREAD

**Issue by Sire** [BlazorExtensions/SignalR#57]
The Javascript ASP.NET Core SignalR client now support [automatic reconnects](https://docs.microsoft.com/en-us/aspnet/core/signalr/javascript-client?view=aspnetcore-3.0#reconnect-clients
), which would be super useful to have.

Stuff needed to be implemented:
- withAutomaticReconnect() function on HubConnectionBuilder
- onreconnecting event on HubConnection
- state property on HubConnection

If this sounds too big, just having the State property on HubConnection would be extremely helpful so we can detect if a (re)connection succeeded or not. 

Thanks for all the work you're putting in! :)

**Comment by galvesribeiro** [comment]
Hello @Sire, do you want to submit a PR on this?

**Comment by Sire** [comment]
Sorry, I just don't have the time. Switched to server-side Blazor also.

**Comment by galvesribeiro** [comment]
Will do that once I find time. Thanks for reporting!

**Comment by galvesribeiro** [comment]
*DEPRECATION NOTE*: This package is no longer required since [Blazor WebAssembly now supports SignalR Client](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/). Users of this package should stop using it and use the official client instead.
