### ISSUE TITLE
Non-generic overload of the On method?

### ISSUE THREAD

**Issue by MichelArendt** [BlazorExtensions/SignalR#59]
Any way to call the non-generic `On `method like the example in the docs?

Example from docs:
`connection.On("Receive", this.Handle);`

If not, any reason why the non-generic is not implemented? I'm trying to accomplish this:
`private void Configure()
{
            HubConnection.On("notify", this.OnConnectedToAPI);
        }
        public void OnConnectedToAPI()
        {
            Console.WriteLine("============================");
        }`

Thanks in advance!

**Comment by galvesribeiro** [comment]
Hey @MichelArendt, thanks for the feedback. 

I'll look into implementing it and see if there is an specific reason we didn't added it before.

Like always, you can make a PR if you few in the mood :)

Thanks!

**Comment by MichelArendt** [comment]
Thanks for the reply @galvesribeiro!

I'd really love to help, but unfortunately I'm not knowledgeable enough atm I'm afraid :(

Thanks for taking this suggestion into consideration! I'll try to implement a workaround or overload on my project for now.

**Comment by galvesribeiro** [comment]
*DEPRECATION NOTE*: This package is no longer required since [Blazor WebAssembly now supports SignalR Client](https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-1-release-now-available/). Users of this package should stop using it and use the official client instead.
