### ISSUE TITLE
Serialization/Deserialization behavior different from SignalR JS/TS client

### ISSUE THREAD

**Issue by ransagy** [BlazorExtensions/SignalR#6]
My use case had me build a hub that only sends data to the client in two methods - one that sends a simple POCO with data (i send it directly, i don't convert it to JSON or serialize it myself) and another that sends an IEnumerable of POCOs (similar to the former, but a different one).

When testing the same hub against a simple JS client, Both are received properly deserialized and "unboxed" - simply the object and the array (as JS interprets it) themselves.

When trying the same with the Blazor client, The single object is received as a SimpleJson.JsonObject class instead while the IEnumerable doesn't arrive and the method callback on the client receives a null object.

Attached is a small repro solution to show the issue - A server running a single SignalR hub with a method for the clients to trigger the two receiving callbacks, A demo JS client and a demo Blazor client - Both with simple button operation to connect and trigger the data callbacks. See the console on both for results.

Thanks!

[SignalRTests.zip](https://github.com/BlazorExtensions/SignalR/files/2207404/SignalRTests.zip)

**Comment by galvesribeiro** [comment]
Fixed with #7 and will be out on 0.1.3. Thanks for the report!

**Comment by ransagy** [comment]
Nice! Thanks for the quick turnaround.
