### ISSUE TITLE
Sending everyone is the same as sending it to me

### ISSUE THREAD

**Issue by corchi72** [BlazorExtensions/SignalR#8]
Hello everything ok and very nice you just have to correct the shipment of messages to everyone, if I misunderstood

<h4>To Everybody</h4>
<form class="form-inline">
    <div class="input-append">
        <input type="text" id="me-message-text" placeholder="Type a message" bind=@_toEverybody />
        <input type="button" id="send" class="btn" value="Send to Me" onclick=@Broadcast />
    </div>
</form>

**Comment by galvesribeiro** [comment]
Hello @corchi72,

Good catch. I've mistakenly broken the test page yesterday while fixing something else.

I've just fixed it, please pull and you will see it correctly.

Thank you!

**Comment by corchi72** [comment]
ok perfect....you are doing a very good job

2018-07-19 16:51 GMT+02:00 Gutemberg Ribeiro <notifications@github.com>:
