### ISSUE TITLE
 Getting on creating connection after update to 0.1.3

### ISSUE THREAD

**Issue by rpedretti** [BlazorExtensions/SignalR#9]
When creating a connection I'm getting a 
`TypeError: Cannot read property 'LogLevel' of undefined at http://localhost:1234/_content/Blazor.Extensions.SignalR.JS:30:10392`

Code:

```
connection = new HubConnectionBuilder()
    .WithUrl($"{baseUrl}/blazorhub", opt =>
    {
        opt.AccessTokenProvider = () => Task.FromResult(Jwt);
        opt.SkipNegotiation = true;
        opt.Transport = HttpTransportType.WebSockets;
     })
     .AddMessagePackProtocol()
     .Build();
```

**Comment by galvesribeiro** [comment]
Hey @rpedretti 

What happens if you set `opt.LogLevel = LogLevel.None;` ?

**Comment by rpedretti** [comment]
It happens to all log levels

**Comment by galvesribeiro** [comment]
Weird... 

I'm trying all combinations here of parameters to try reproduce what you are facing without success: 

![image](https://user-images.githubusercontent.com/4714040/43023958-0a2ba66a-8c43-11e8-9d9b-e665340c40c8.png)

Could you put together a very small project with a repro case somewhere so I can test it?

**Comment by rpedretti** [comment]
Ok. I cleared the nuget cache, removed all references from project by hand and it connected, including the token factory. The server register the connection Id but on evry callback I'm getting a
```
Error: Cannot deserialize JSON into type 'System.Threading.Tasks.Task' because it does not have a public parameterless constructor.
    at invokeDotNetMethodCore (InvokeDotNetMethodWithJsonMarshalling.ts:107)
    at Object.invokeDotNetMethodAsync (InvokeDotNetMethodWithJsonMarshalling.ts:129)
    at t.<anonymous> (HubConnectionManager.ts:101)
...
```

I also cloned the project and added the references to my proj to see if it was a build problem, but the same occurs.

To test, i have a hub published at [http://blazorsignalr.azurewebsites.net](http://blazorsignalr.azurewebsites.net). It does not require auth, so its just connect and subsribe to the `connected` event

**Comment by galvesribeiro** [comment]
Cool! Thanks! Please let me know if you have further issues. Closing for now.

**Comment by galvesribeiro** [comment]
Also, just to let you know. If the hub you are connecting come from the same base address of the Blazor app (meaning it is on the asp.net server hosting Blazor), you don't need to specify the full Url at the `.WithUrl()`. You just need the relative path there as I did on the sample and the picture I pasted here.

**Comment by rpedretti** [comment]
They are not on the same app. I have a web API app to host the hubs and security and client apps. But thanks for the info!
